/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yk.opic.project.server;

import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
//        ServerApp classUnderTest = new ServerApp();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
